exclude: |
  (?x)^(
      chain/.*|
      exchange/.*|
      proto/.*
  )$
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: end-of-file-fixer
        -   id: check-yaml
  -   repo: https://github.com/dnephin/pre-commit-golang
      rev: master
      hooks:
        - id: go-fmt
        - id: go-imports
        - id: golangci-lint
          args: [--timeout=15m]
